### PR TITLE
Fix more 1.92 Clippies

### LINKED ISSUE #1895: Clippy: Address large struct/enum variants
As part of PR #1894, we added `--allow` for `clippy::large_enum_variant` and `clippy::result-large-err` (`--allow unused` is #1893). We want to remove this lint exception, but some existing large structs might be architecturally necessary. This is a follow-up issue to investigate what we can `Box` and what we need to `#[allow]`/`#[expect]`

### PR DESCRIPTION
**Pull request by iostat**
### Description

Addresses the `clippy::{large_enum_variants,result_large_err}` lints introduced by the 1.92 upgrade. Some enum variants were boxed where it made sense, others we're allowed as the size difference between the largest/second-largest wasn't too big to warrant a larger refactor. 

Removes the `--allow clippy::{large_enum_variants,result_large_err}` from `make lint[-beta]`

Additionally, the `--allow unused` was changed to `--allow unused_assignments`, which is the more specific lint that was triggering #1893. Seeing as that's likely a compiler bug, we're keeping that issue open. However, `--allow unused` did allow some `dead_code` to slip through the cracks, so that's been addressed here too.

### Related Issue(s)

Closes #1895 

### Type of Change

- [x] Refactoring (no functional changes)
- [x] Performance improvement (potentially! some multi-kb structures were moved from stack to heap)

### Testing

Code should compile and CI should pass. There are no functional changes in this PR.

### Changelog Entry

- **Fixed**: **CI**: Remove clippy exceptions for large enum/err variants added as part of the Rust 1.92 upgrade

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -262,16 +262,12 @@ format-md: ## Format all markdown and MDX files to wrap at 80 characters
 .PHONY: lint
 lint: ## Run linter (clippy)
 	cargo clippy --all-targets -- -D warnings \
-	  --allow clippy::large_enum_variant \
-	  --allow clippy::result-large-err \
-	  --allow unused
+	  --allow unused_assignments
```
Comment (richardpringle) [inline Makefile:265]: Oh no... for the whole thing!?

Comment (richardpringle) [reply Makefile:265]: (I actually don't know the difference between `unused_assignments` vs `unused`)

File: crates/ledger/src/proofs/transaction.rs [hunk 2]
```diff
@@ -4397,6 +4397,7 @@ pub(super) mod tests {
 
     /// External worker input.
     #[derive(Debug, BinProtRead, BinProtWrite)]
+    #[expect(clippy::large_enum_variant, reason = "This enum is only used in tests")]
```
Comment (richardpringle) [inline crates/ledger/src/proofs/transaction.rs:4400]: We should put this behind a feature flag if it's only used in tests

Comment (richardpringle) [reply crates/ledger/src/proofs/transaction.rs:4400]: Don't need to change in this PR, but can you create an issue before resolving the comment?

File: crates/ledger/src/scan_state/scan_state.rs [hunk 3]
```diff
@@ -2142,7 +2142,10 @@ impl ScanState {
                     }
                 };
 
-                Ok(snark_work::spec::Work::Transition((statement, witness)))
+                Ok(snark_work::spec::Work::Transition((
+                    statement,
+                    Box::new(witness),
```
Comment (richardpringle) [inline crates/ledger/src/scan_state/scan_state.rs:2147]: Curious to hear your opinion on this, but when it comes to wrapper types like this, I prefer to use `witness.into()`. That way, changes are minimized if we decide to have any other wrapper or anything like that. 

(not a change for this PR, just interested in your thoughts)

File: crates/ledger/src/scan_state/snark_work.rs [hunk 4]
```diff
@@ -30,6 +30,7 @@ mod tests {
 
     /// External worker input.
     #[derive(Debug, BinProtRead, BinProtWrite)]
+    #[expect(clippy::large_enum_variant, reason = "This enum is only used in tests")]
```
Comment (richardpringle) [inline crates/ledger/src/scan_state/snark_work.rs:33]: Same comment

File: crates/node/src/event_source/event_source_actions.rs [hunk 5]
```diff
@@ -3,6 +3,7 @@ use serde::{Deserialize, Serialize};
 pub type EventSourceActionWithMeta = redux::ActionWithMeta<EventSourceAction>;
 
 #[derive(Serialize, Deserialize, Debug, Clone)]
+#[expect(clippy::large_enum_variant, reason = "This enum extends super::Event")]
```
Comment (richardpringle) [inline crates/node/src/event_source/event_source_actions.rs]: 🤔 I'm not sure if I agree with this one. This should almost certainly be boxed, no?

Also... a nit... but... I would say "wraps," not "extends"

File: crates/node/src/event_source/event_source_effects.rs [hunk 6]
```diff
@@ -489,7 +486,9 @@ pub fn event_source_effects<S: Service>(store: &mut Store<S>, action: EventSourc
             Event::GenesisLoad(res) => match res {
                 Err(err) => todo!("error while trying to load genesis config/ledger. - {err}"),
                 Ok(data) => {
-                    store.dispatch(TransitionFrontierGenesisAction::LedgerLoadSuccess { data });
+                    store.dispatch(TransitionFrontierGenesisAction::LedgerLoadSuccess {
+                        data: Box::new(data),
```
Comment (richardpringle) [inline crates/node/src/event_source/event_source_effects.rs:490]: Again, this is one of those places where I would use `Into::into`, just because it means this code doesn't change if the size of `data` changes

File: crates/node/src/ledger/ledger_manager.rs [hunk 7]
```diff
@@ -22,38 +22,48 @@ use std::collections::BTreeMap;
 /// can't be expressed in the Rust type system at the moment. For this
 /// reason this type is private while functions wrapping the whole call
 /// to the service are exposed as the service's methods.
-#[allow(dead_code)] // TODO
```
Comment (richardpringle) [inline crates/node/src/ledger/ledger_manager.rs:25]: 😳

File: crates/node/src/ledger/ledger_manager.rs [hunk 8]
```diff
@@ -22,38 +22,48 @@ use std::collections::BTreeMap;
...
+#[expect(
```
Comment (richardpringle) [inline crates/node/src/ledger/ledger_manager.rs:25]: `expect`?

File: crates/node/src/ledger/ledger_service.rs [hunk 9]
```diff
@@ -1271,7 +1271,7 @@ impl LedgerCtx {
             .view()
             .map(|jobs| {
                 let jobs = jobs.collect::<Vec<JobValueWithIndex<'_>>>();
-                let mut iter = jobs.iter().peekable();
+                let iter = jobs.iter().peekable();
```
Comment (richardpringle) [inline crates/node/src/ledger/ledger_service.rs:1274]: 😎

File: crates/node/src/transition_frontier/genesis/transition_frontier_genesis_reducer.rs [hunk 10]
```diff
@@ -45,7 +45,7 @@ impl TransitionFrontierGenesisState {
             TransitionFrontierGenesisAction::LedgerLoadSuccess { data } => {
                 *state = Self::LedgerLoadSuccess {
                     time: meta.time(),
-                    data: data.clone(),
+                    data: *data.clone(),
```
Comment (richardpringle) [inline crates/node/src/transition_frontier/genesis/transition_frontier_genesis_reducer.rs:47]: Really!? `Clone::clone` should always return an owned type, no?

Comment (richardpringle) [reply crates/node/src/transition_frontier/genesis/transition_frontier_genesis_reducer.rs:47]: Ah nvm... `data` is `&Box`

File: tools/testing/src/scenario/event_details.rs [hunk 11]
```diff
@@ -8,14 +8,13 @@ use node::{
...
-        let rpc_state = &state.p2p.get_ready_peer(peer_id)?.channels.rpc;
-        if *req_id == rpc_state.pending_local_rpc_id()? {
-            return Some(format!("Request: {}", rpc_state.pending_local_rpc()?));
+    // this could be a let-chain but we're on rust 2021 instead of 2024 >:(
+    if let Event::P2p(P2pEvent::Channel(P2pChannelEvent::Received(peer_id, Ok(msg)))) = event {
+        if let ChannelMsg::Rpc(RpcChannelMsg::Response(req_id, _)) = &**msg {
+            let rpc_state = &state.p2p.get_ready_peer(peer_id)?.channels.rpc;
+            if *req_id == rpc_state.pending_local_rpc_id()? {
+                return Some(format!("Request: {}", rpc_state.pending_local_rpc()?));
+            }
```
Comment (richardpringle) [inline tools/testing/src/scenario/event_details.rs:17]: This is gross... but it was gross before... I just couldn't look at it without commenting

File: crates/p2p/src/service_impl/webrtc/mod.rs
Comment (richardpringle) [inline crates/p2p/src/service_impl/webrtc/mod.rs:1]: yikes

**Review by richardpringle — DISMISSED** [review]

File: Makefile (hunk 1 above)
Comment (iostat) [reply Makefile:265]: `unused` is every kind of unused, including `_assignments`, `_variables`, `_muts`, `_imports`, and I believe `dead_code`. `unused_assignments` is just assignments

File: crates/ledger/src/proofs/transaction.rs (hunk 2 above)
Comment (iostat) [reply crates/ledger/src/proofs/transaction.rs:4400]: It's already inside `#[cfg(test)] pub(super) mod tests`...

File: crates/ledger/src/scan_state/scan_state.rs (hunk 3 above)
Comment (iostat) [reply crates/ledger/src/scan_state/scan_state.rs:2147]: I prefer to be explicit... Into can occasionally confuse the compiler when it's trying to resolve a lot of potentially applicable instances (happens when you love your generics). Moreover, being explicit allows you to see the surface area with the errors you're going to have to address when you change the container, forcing you to be more considerate of your change

File: crates/ledger/src/scan_state/snark_work.rs (hunk 4 above)
Comment (iostat) [reply crates/ledger/src/scan_state/snark_work.rs:33]: Similarly, already within `#[cfg(test)] mod tests`.

File: crates/node/src/event_source/event_source_actions.rs (hunk 5 above)
Comment (iostat) [reply crates/node/src/event_source/event_source_actions.rs]: The large_enum_variant lint gets triggered not when your structure itself is large, but when there's a large size difference between the largest and second-largest variants of the enum, implying that in many cases, there's a lot of wasted space allocated to variants that don't need it. In this case, I'm considering how the data is actually being used. In many ways, this enum is like a "spicy `Option<Event>`" -- i.e., it has a reason for being `None` (one of the three variants besides `NewEvent`), but if there **is** `Some(Event)`, you probably want it already on the stack to be processed, and the heap indirection would be inefficient

File: crates/node/src/ledger/ledger_manager.rs (hunk 8 above)
Comment (iostat) [reply crates/node/src/ledger/ledger_manager.rs:25]: It's like `#[allow]`, but if the warning **isn't** triggered it throws a warning/error. So if you've addressed the issue that led to the `#[allow]` in the first place, you're forced to remove it. 

https://users.rust-lang.org/t/dont-allow-expect-and-be-reasonable/136078

Comment (iostat) [reply crates/node/src/ledger/ledger_manager.rs:25]: In fact, that `#[allow(dead_code)]` I removed in the line right above is a prime example of why you should prefer `#[expect]` :)

File: crates/p2p/src/service_impl/webrtc/mod.rs
Comment (iostat) [reply crates/p2p/src/service_impl/webrtc/mod.rs:1]: I'm guessing you mean the ton of changes below -- it's effectively an indentation change but looks dumb in the diff. I had to add a deref to the Box in External, but the matches before had several arms for different variants of the PeerCmd inside External.

File: tools/testing/src/scenario/event_details.rs (hunk 11 above)
Comment (iostat) [reply tools/testing/src/scenario/event_details.rs:17]: image

(agreed)

File: crates/node/src/event_source/event_source_actions.rs (hunk 5 above)
Comment (iostat) [reply crates/node/src/event_source/event_source_actions.rs]: Agree on "wraps" -> "extends"

File: Makefile (hunk 1 above)
Comment (iostat) [reply Makefile:265]: Ideally we take it out when the compiler issue in #1893 is addressed ;)

**Review by dannywillems — APPROVED** [review]
Bumping @richardpringle approval
